In [27]:
import numpy as np

a = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])

print(a)
print()
print(a[0])


[[1 2 3 4]
 [5 6 7 8]]

[1 2 3 4]


> a 의 경우 첫번째 축의 길이가 2, 두번째 축의 길이가 4가 된다.

In [28]:
b = np.array([1,2,3])

In [29]:
np.zeros(2)

array([0., 0.])

In [30]:
np.ones(2)

array([1., 1.])

In [31]:
np.empty(4)

array([ 2.5,  5. ,  7.5, 10. ])

In [32]:
np.arange(4)

array([0, 1, 2, 3])

In [33]:
np.arange(2,9,2)

array([2, 4, 6, 8])

위의 상황을 보면 2~ 9 까지의 범위중 2 간격으로 arange Array를 만든것을 볼수 있다. 이와 유사하게 linspace도 사용해 줄수 있는데 이는 3번째 args로 들어간 숫자만큼 잘라서 array에 넣어준다는 것이다.


In [34]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [35]:
array = np.ones(2, dtype=int) #dtype을 명시하여서 data type을 특정지을수 있다. 이렇게 해주지않으면 기본 자료형은 float64가 된다.
array

array([1, 1])

# Method

np.append()
np.delete()
np.sort()

In [62]:
arr = np.array([1,2,3])
arr

array([1, 2, 3])

In [63]:
arr = np.append(arr,[4,5])
arr

array([1, 2, 3, 4, 5])

In [64]:
arr = np.delete(arr,1) # 1번째 index를 삭제한다.
arr

array([1, 3, 4, 5])

In [67]:
sort_arr = np.array([2,3,5,6,1,2,3])
sort_arr = np.sort(sort_arr)
sort_arr

array([1, 2, 2, 3, 3, 5, 6])

# Shape And Size

ndarray.ndim() : 축(차원)의 갯수를 알려준다.  
ndarray.size() : array의 전체 element 갯수를 알려준다.   
ndarray.shape() : 각 차원마다 들고있는 element의 갯수를 보여준다.  


In [77]:
array_example = np.array([[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]],[[0,1,2,3],[4,5,6,7]]])
array_example

array([[[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]],

       [[0, 1, 2, 3],
        [4, 5, 6, 7]]])

In [78]:
array_example.ndim


3

In [79]:
array_example.size

24

In [80]:
array_example.shape #밖에서부터 체크하면서 들어가는데 1차 축 2차 축 3차 축의 element갯수를 체크해본다.

(3, 2, 4)

# reShape()

In [83]:
a = np.arange(6)
a

array([0, 1, 2, 3, 4, 5])

In [85]:
b = a.reshape(3,2)
b

array([[0, 1],
       [2, 3],
       [4, 5]])

# Add New Axis to Array

np.newaxis
np.expand_dims

In [86]:
c = np.arange(6)
c.shape

(6,)

In [87]:
d = a[np.newaxis]
d.shape

(1, 6)

In [89]:
row_vector = a[np.newaxis , :]

print(row_vector)
row_vector.shape


[[0 1 2 3 4 5]]


(1, 6)

In [90]:
col_vector = a[:,np.newaxis]
print(col_vector)
col_vector.shape

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]]


(6, 1)

In [91]:
a = np.arange(6)
a.shape

(6,)

In [93]:
b = np.expand_dims(a,axis=1)
b.shape

(6, 1)

In [94]:
c = np.expand_dims(a,axis=0)
c.shape

(1, 6)

In [97]:
data = np.array([1,2,3])

print(data[0])
print(data[1])
print(data[0:2])
print(data[1:])
print(data[-2:]) #맨 뒤 인덱스부터 -1로 계산하여 slicing해준다.

1
2
[1 2]
[2 3]
[2 3]


In [98]:
a = np.array([[1 , 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])


In [100]:
print(a[a<7])

[1 2 3 4 5 6]


In [101]:
big_five = (a >= 5)
print(a[big_five])

[ 5  6  7  8  9 10 11 12]


In [102]:
print(a[a%2 ==0])

[ 2  4  6  8 10 12]


In [103]:
print(a[(a>2) & (a< 11)])

[ 3  4  5  6  7  8  9 10]


In [104]:
five_up = (a>5)

print(five_up)

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [105]:
b = np.where(a < 5) #5보다 작은 요소들으 색인을 가져올수 있다.
print(b) #이때 아래와 같이 첫번째 array는 row index, 두번째는 column index를 나타낸다.

(array([0, 0, 0, 0], dtype=int64), array([0, 1, 2, 3], dtype=int64))


In [106]:
list_of_coordinates = list(zip(b[0],b[1]))

for cord in list_of_coordinates:
    print(cord)

(0, 0)
(0, 1)
(0, 2)
(0, 3)


In [107]:
print(a[b])

[1 2 3 4]


In [108]:
not_there = np.where(a==42)
print(not_there)

(array([], dtype=int64), array([], dtype=int64))


# create an Array from existing data

np.vstack()
np.hstack()
no.hsplit()

.view()
.copy()

In [109]:
a_1 = np.array([[1,1],[2,2]])
a_2 = np.array([[3,3],[4,4]])

In [110]:
np.vstack((a_1,a_2))

array([[1, 1],
       [2, 2],
       [3, 3],
       [4, 4]])

In [111]:
np.hstack((a_1,a_2))

array([[1, 1, 3, 3],
       [2, 2, 4, 4]])

> 위의 예에서 보면 알 수 있지만 hstack은 horizontal stack으로 가로로 쌓아 나가는 반면 v stack은 vertical 방향으로 쌓아나간다.


In [113]:
a = np.array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
     [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])
a

array([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12],
       [13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [115]:
np.hsplit(a,4)

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5,  6],
        [16, 17, 18]]),
 array([[ 7,  8,  9],
        [19, 20, 21]]),
 array([[10, 11, 12],
        [22, 23, 24]])]

In [119]:
np.hsplit(a,(3,5)) #이렇게 작성해주면 3까지, 그리고 3~5, 5~ 의 범위를 나누어서 split해준다.

[array([[ 1,  2,  3],
        [13, 14, 15]]),
 array([[ 4,  5],
        [16, 17]]),
 array([[ 6,  7,  8,  9, 10, 11, 12],
        [18, 19, 20, 21, 22, 23, 24]])]

In [123]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [125]:
b = np.reshape(a,(3,4))
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [127]:
c = b.view() #shallow copy
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [128]:
d =  b.copy() #deep copy

# Array operator

기본적으로 사칙연산은 다 가능하다.

In [129]:
a = np.array([1,2,3,4])
a.sum()

10

In [130]:
b = np.array([[1,1],[2,2]])

b.sum(axis = 0)

array([3, 3])

In [131]:
b.sum(axis=1)

array([2, 4])

# BroadCasting

dim이 안맞아서 연산을 할수 없는 경우에는 자동으로 확장을 하여서 연산을 진행한다.


In [132]:
b * 1.6

array([[1.6, 1.6],
       [3.2, 3.2]])

In [133]:
b.max()

2

In [134]:
b.min()

1

In [135]:
b.sum()

6

In [139]:
a = np.array([[1,2,3],[0,0,6]])

a.min(axis=0) #이렇게하면 0번째 축인 각 list를 서로 비교해서 각 인덱스마다의 min값을 가져온다.

array([0, 0, 3])

# 각 축의 size 확인하기

np.size(arr, 축 index)


# matrices

In [143]:
data = np.array([[1,2],[3,4]])
data

array([[1, 2],
       [3, 4]])

In [141]:
data[0,1]

2

In [142]:
data[1:3]

array([[3, 4]])

In [146]:
data[0:2,0]

array([1, 3])

In [148]:
np.ones((4,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [149]:
np.ones(3)

array([1., 1., 1.])

In [150]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

# unique

In [154]:
a = np.array([11, 11, 12, 13, 14, 15, 16, 17, 12, 13, 11, 14, 18, 19, 20])

In [155]:
np.unique(a) # np.unique(a, return_index=True) 인덱스를 반환 받을 수도 있다.


array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [156]:
unique_val , occurrence_cnt = np.unique(a, return_counts=True)

In [157]:
print(unique_val, occurrence_cnt)

[11 12 13 14 15 16 17 18 19 20] [3 2 2 2 1 1 1 1 1 1]


In [165]:
a2D = np.array([[1, 2, 3, 4] ,[5, 6, 7, 8] , [9, 10, 11, 12],  [1, 2, 3, 4]])

In [166]:
np.unique(a2D)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [167]:
np.unique(a2D, axis=0)

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [169]:
unique_rows, occur_cnt, indices = np.unique(a2D, axis=0, return_counts=True,return_index=True)

print(unique_rows)
print()
print(occur_cnt)
print()
print(indices)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

[0 1 2]

[2 1 1]


# Transpose and reShape a matrix
np.reshape()
np.transpose()
np.T()

In [171]:
data = np.arange(6)
data

array([0, 1, 2, 3, 4, 5])

In [172]:
data.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [173]:
data.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [174]:
np.transpose(data.reshape(3,2)) #여기서

array([[0, 2, 4],
       [1, 3, 5]])

In [175]:
np.flip(data.reshape(3,2)) #얘는 행과 열을 reverse한다.
# np.flip(arr2D, axis=0) 이렇게 명시적으로 축을 지정해준 경우 해당 축만 reverse해준다.


array([[5, 4],
       [3, 2],
       [1, 0]])

In [177]:
# 이때 matrix의 특정 column만 찾아 들어갈 경우 해당 column의 값들만 reverse해줄 수도 있다.
a = np.arange(12).reshape(3,4)
a[:,1] = np.flip(a[:,1])
print(a)

[[ 0  9  2  3]
 [ 4  5  6  7]
 [ 8  1 10 11]]


# 다차원 모델의 모양 변경 및 병합

.flatten(), .ravel()

In [190]:
arr = np.arange(12)
arr = np.reshape(arr,(3,4))
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [193]:
arr.flatten()  #1차원으로 배열을 평탄화시킨다.

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [194]:
arr2 = arr.flatten()
arr2[0] = 100
print("original")
print(arr)
print("New array")
print(arr2)

original
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
New array
[100   1   2   3   4   5   6   7   8   9  10  11]


In [196]:
arr3 = arr.ravel() #이처럼 Rank를 쓰면 복사한 객체의 변경사항이 부모에게까지 영향을 미친다.
arr3[0] = 101
print("original")
print(arr)
print("New array")
print(arr3)


original
[[101   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]]
New array
[101   1   2   3   4   5   6   7   8   9  10  11]


# 도움을 청하는 방법

In [198]:
help(max)

Help on built-in function max in module builtins:

max(...)
    max(iterable, *[, default=obj, key=func]) -> value
    max(arg1, arg2, *args, *[, key=func]) -> value
    
    With a single iterable argument, return its biggest item. The
    default keyword-only argument specifies an object to return if
    the provided iterable is empty.
    With two or more arguments, return the largest argument.



In [199]:
max?

Docstring:
max(iterable, *[, default=obj, key=func]) -> value
max(arg1, arg2, *args, *[, key=func]) -> value

With a single iterable argument, return its biggest item. The
default keyword-only argument specifies an object to return if
the provided iterable is empty.
With two or more arguments, return the largest argument.
Type:      builtin_function_or_method


In [200]:
a = np.arange(12)

In [201]:
a?

Type:            ndarray
String form:     [ 0  1  2  3  4  5  6  7  8  9 10 11]
Length:          12
File:            c:\users\jangc\appdata\local\programs\python\python39\lib\site-packages\numpy\__init__.py
Docstring:       <no docstring>
Class docstring:
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see N

In [203]:
def double(a):
    '''Return a *2 '''
    return a * 2

In [204]:
double?

Signature: double(a)
Docstring: Return a *2 
File:      c:\users\jangc\desktop\개인\portpolio\study\2021\forkaggle\data\numpy\<ipython-input-203-bb7080d5174d>
Type:      function


In [206]:
double??

Signature: double(a)
Source:   
def double(a):
    '''Return a *2 '''
    return a * 2
File:      c:\users\jangc\desktop\개인\portpolio\study\2021\forkaggle\data\numpy\<ipython-input-203-bb7080d5174d>
Type:      function


In [207]:
len?

Signature: len(obj, /)
Docstring: Return the number of items in a container.
Type:      builtin_function_or_method


# 수식으로의 np

MeanSquareError = (1/n) * np.sum(np.square(predictions - labels))

# np객체의 저장과 불러오기

np.save()
np.savez()
np.savetxt()
np.load()
np.loadtxt()

In [208]:
arr = np.arange(6)
np.save('filename',arr)

In [209]:
b = np.load('filename.npy')

In [210]:
print(b)

[0 1 2 3 4 5]


In [214]:
csv_arr = np.arange(10)
csv_arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [215]:
np.savetxt('new_file.csv',csv_arr)

In [217]:
np.loadtxt('new_file.csv') #allow_pickle=False 옵션을 주면 신뢰할수 있는 내용에 대해서 가져온다. 

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])